# Note the version (ver1, ver2, ...) folder generated by generate_arch.py and use those versions for scheduling below
python3 generate_arch.py --crypt_engine_type parallel --sram_depth 8192 # 131kB, ver0
python3 generate_arch.py --crypt_engine_type pipeline --sram_depth 8192 # 131kB, ver5
python3 generate_arch.py --crypt_engine_type parallel --sram_depth 2048 # 32kB, ver6
python3 generate_arch.py --crypt_engine_type pipeline --sram_depth 2048 # 32kB, ver7
python3 generate_arch.py --crypt_engine_type parallel --sram_depth 1024 # 16kB, ver8
python3 generate_arch.py --crypt_engine_type pipeline --sram_depth 1024 # 16kB, ver9

# 32kB, parallel
python3 scheduler.py --arch designs/eyeriss_like/ver6 --workload alexnet --scheduler baseline-timeloop-only
python3 scheduler.py --arch designs/eyeriss_like/ver6 --workload alexnet --scheduler crypt-opt-cross

# # 32kB, pipeline
python3 scheduler.py --arch designs/eyeriss_like/ver7 --workload alexnet --scheduler baseline-timeloop-only
python3 scheduler.py --arch designs/eyeriss_like/ver7 --workload alexnet --scheduler crypt-opt-cross

# 16kB, parallel
python3 scheduler.py --arch designs/eyeriss_like/ver8 --workload alexnet --scheduler baseline-timeloop-only
python3 scheduler.py --arch designs/eyeriss_like/ver8 --workload alexnet --scheduler crypt-opt-cross

# 16kB, pipeline
python3 scheduler.py --arch designs/eyeriss_like/ver9 --workload alexnet --scheduler baseline-timeloop-only
python3 scheduler.py --arch designs/eyeriss_like/ver9 --workload alexnet --scheduler crypt-opt-cross